### ISSUE TITLE
Error while installing on site the version-3

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/insights#378] opened 2024-12-05 10:41 UTC
bench install-app insights

Installing insights...
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/commands/site.py", line 478, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/installer.py", line 332, in install_app
    sync_fixtures(name)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 22, in sync_fixtures
    import_fixtures(app)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 41, in import_fixtures
    import_doc(file_path)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 265, in import_doc
    import_file_by_path(
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 125, in import_file_by_path
    db_modified_timestamp = frappe.db.get_value(doc["doctype"], doc["name"], "modified")
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 514, in get_value
    result = self.get_values(
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 618, in get_values
    out = self._get_values_from_table(
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 891, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 257, in sql
    traceback.print_stack()
"Error in query:\n('SELECT `modified` FROM `tabInsights Data Source` WHERE `name`=%(param1)s ORDER BY `modified` DESC LIMIT 1', {'param1': 'Site DB'})"
Skipping fixture syncing from the file insights_data_source.json. Reason: Module import failed for Insights Data Source, the DocType you're trying to open might be deleted.
Error: No module named 'frappe.core.doctype.insights_data_source'
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/commands/site.py", line 478, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/installer.py", line 332, in install_app
    sync_fixtures(name)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 22, in sync_fixtures
    import_fixtures(app)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 41, in import_fixtures
    import_doc(file_path)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 265, in import_doc
    import_file_by_path(
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 125, in import_file_by_path
    db_modified_timestamp = frappe.db.get_value(doc["doctype"], doc["name"], "modified")
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 514, in get_value
    result = self.get_values(
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 618, in get_values
    out = self._get_values_from_table(
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 891, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 257, in sql
    traceback.print_stack()
"Error in query:\n('SELECT `modified` FROM `tabInsights Notebook` WHERE `name`=%(param1)s ORDER BY `modified` DESC LIMIT 1', {'param1': 'Uncategorized'})"
Skipping fixture syncing from the file insights_notebook.json. Reason: Module import failed for Insights Notebook, the DocType you're trying to open might be deleted.
Error: No module named 'frappe.core.doctype.insights_notebook'
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/commands/site.py", line 478, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/installer.py", line 332, in install_app
    sync_fixtures(name)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 22, in sync_fixtures
    import_fixtures(app)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 41, in import_fixtures
    import_doc(file_path)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 265, in import_doc
    import_file_by_path(
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 125, in import_file_by_path
    db_modified_timestamp = frappe.db.get_value(doc["doctype"], doc["name"], "modified")
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 514, in get_value
    result = self.get_values(
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 618, in get_values
    out = self._get_values_from_table(
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 891, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/dineshpanchal/bench/v15-1/frappe-bench/apps/frappe/frappe/database/database.py", line 257, in sql
    traceback.print_stack()
"Error in query:\n('SELECT `modified` FROM `tabInsights Data Source v3` WHERE `name`=%(param1)s ORDER BY `modified` DESC LIMIT 1', {'param1': 'Site DB'})"
Skipping fixture syncing from the file insights_data_source_v3.json. Reason: Module import failed for Insights Data Source v3, the DocType you're trying to open might be deleted.
Error: No module named 'frappe.core.doctype.insights_data_source_v3'
Updating Dashboard for insights

**Comment by nextchamp-saqib** [comment] 2024-12-09 10:09
duplicate of https://github.com/frappe/insights/issues/360

**Closed by nextchamp-saqib** 2024-12-09 10:09 UTC
