### ISSUE TITLE
Table not shown using Inner Join

### ISSUE THREAD

**Issue by pinxaolives** [frappe/insights#129] opened 2023-05-31 15:08 UTC
**Description of the issue**

Problem using inner joins. The SQL statement is:

SELECT t0.*
FROM tabEscala TSO AS t0
INNER JOIN tabEscala De Jong Gierveld AS t1
ON t0.owner = t1.owner
LIMIT 500

Left table is shown but the right table is not…

![image](https://github.com/frappe/insights/assets/40894766/c2b9df6b-1a8a-4a96-8314-62e8cb8610f4)

**Context information (for bug reports)**

**Output of bench version**
Version 14

**Steps to reproduce the issue**

**Expected result**

Stacktrace / full error message
No errors shown

**Additional information**
OS: Ubuntu
Edge

**Frappe install method:** 

Frappe Cloud

**Comment by nextchamp-saqib** [comment] 2023-06-02 05:11
This is a known issue.
Ref. https://github.com/frappe/insights/issues/118#issuecomment-1554735565

The issue is with the SQL itself and not with the application

**Comment by nextchamp-saqib** [comment] 2023-08-05 15:26
Currently it is the expected behavior so closing the issue

**Closed by nextchamp-saqib** 2023-08-05 15:26 UTC
