### ISSUE TITLE
Error in Explore a dummy database

### ISSUE THREAD

**Issue by Shankarv19bcr** [frappe/insights#46] opened 2022-10-25 06:47 UTC
![issue](https://user-images.githubusercontent.com/95605398/197701561-25396bee-866e-4cab-930e-941ebbd992ca.png)

**Comment by NagariaHussain** [comment] 2022-10-25 07:13
I think the issue is that the function `is_job_queued` only exists in `develop` and not version 14: https://github.com/frappe/frappe/pull/18091 .

**Comment by nextchamp-saqib** [comment] 2022-10-25 10:03
I'll get this fixed. For now, you can go to Insights Settings and check "setup complete" and then open Insights

**Comment by nextchamp-saqib** [comment] 2022-10-27 08:16
Fixed with 1cdb279e2a5888ea4bdf5e2250033de74865c958

**Closed by nextchamp-saqib** 2022-10-27 08:16 UTC
Labels: bug
